[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "2.0.95"
actix-web = "4.4"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
yup-oauth2 = "8.3"
tokio = { version = "1.28", features = ["full", "macros"] }
log = "0.4"
env_logger = "0.10"
google-sheets4 = "5.0"     # 예: 5.0.5+20240621
hyper = "0.14"
hyper-rustls = "0.24"
serde_json = "1.0"
dotenv = "0.15"